### PR TITLE
Fix installer readme

### LINKED ISSUE #2: Generated README instructions always use npm
Even if the user chose to manage dependencies with yarn.

### PR DESCRIPTION
**Pull request by MattCheely**
Fixes #2

### CODE REVIEW

File: generators/app/index.js [hunk 1]
```diff
@@ -51,22 +51,13 @@ module.exports = class extends Generator {
...
   async install() {
-    let choice = await this.prompt([
-      {
-        name: "installer",
-        message: "What would you like to use to install dependencies?",
-        type: "list",
-        choices: ["npm", "yarn", "skip"]
-      }
-    ]);
+    let installer = this.answers.installer;
```
Comment (kalutheo) [inline generators/app/index.js]: should be `const installer` as this value is not mutated

File: lib/options-parser.js [hunk 2]
```diff
@@ -1,5 +1,7 @@
 const commander = require("commander");
 
+let errors = [];
```
Comment (kalutheo) [inline lib/options-parser.js]: same here `const errors`

**Comment by kalutheo** [comment]
ok good to go @MattCheely
